-- ============================================================
-- ShopPulse Analytics
-- Business Questions
-- PostgreSQL
-- ============================================================


-- Q1. What is the total revenue generated by gender?

SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;


-- ============================================================
-- Q2. Which customers used a discount but still spent
--     above the average purchase amount?
-- ============================================================

SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  )
ORDER BY purchase_amount DESC;


-- ============================================================
-- Q3. What are the top 5 products by average review rating?
-- ============================================================

SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;


-- ============================================================
-- Q4. How does average purchase amount differ between
--     Standard and Express shipping?
-- ============================================================

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;


-- ============================================================
-- Q5. Do subscribed customers spend more?
-- ============================================================

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- ============================================================
-- Q6. Which 5 products have the highest percentage
--     of discounted purchases?
-- ============================================================

SELECT
    item_purchased,
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- ============================================================
-- Q7. Segment customers into New, Returning and Loyal
--     based on previous purchases.
-- ============================================================

WITH customer_segments AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM customer_segments
GROUP BY customer_segment
ORDER BY customer_count DESC;


-- ============================================================
-- Q8. What are the top 3 products within each category?
-- ============================================================

WITH product_rankings AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS product_rank
    FROM customer
    GROUP BY
        category,
        item_purchased
)

SELECT
    category,
    product_rank,
    item_purchased,
    total_orders
FROM product_rankings
WHERE product_rank <= 3
ORDER BY
    category,
    product_rank;


-- ============================================================
-- Q9. Are repeat buyers with more than 5 previous purchases
--     also likely to subscribe?
-- ============================================================

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;


-- ============================================================
-- Q10. What is the revenue contribution of each age group?
-- ============================================================

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;